import = [
  "~/.config/alacritty/rose-pine.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.5

# [colors]
# cursor = { text = "#000000", cursor = "#ffffff" }

[window]
dimensions = { columns = 100, lines = 40 }
opacity = 0.98
startup_mode = "SimpleFullscreen"

[env]
TERM = "xterm-256color"

