import = [
  # uncomment the flavour you want below:
    # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.5

[window]
dimensions = { columns = 100, lines = 40 }
opacity = 0.98
startup_mode = "SimpleFullscreen"

[env]
 TERM = "xterm-256color"

