import = [
  "~/.config/alacritty/rose-pine.toml"
]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.5

[window]
decorations = "None"
dimensions = { columns = 80, lines = 24 }
opacity = 0.98
# blur = true
startup_mode = "SimpleFullscreen"

[colors.primary]
# background = "#121212"

# [env]
# TERM = "xterm-256color"

